name: Build tests

on: [push]
# on:
#   pull_request:
#     branches:
#       - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    # runs-on: python:latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.8" 
        cache: "pip" # caching pip dependencies
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install dependencies and pydaes (pydaes)
      run: pip install -e .
    - name: Install test dependencies
      run: pip install pytest
    - name: Test with pytest
      run: pytest ./test/
